services:
  api:
    build: .
    container_name: saas_api
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/saas_subscription?replicaSet=rs0
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: saas_mongo
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - saas_mongo_data:/data/db
    healthcheck:
      test: mongosh --quiet --eval "try { rs.status().ok } catch (e) { rs.initiate().ok }"
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  saas_mongo_data:
